In [2]:
import numpy as np

In [3]:
arr = np.array([1,2,3,4,5])

In [4]:
print(arr)

[1 2 3 4 5]


In [5]:
arr1 = np.array([1,2,3])
arr2 = np.array([2,1,4])

In [6]:
print(arr1)
print(arr2)
print(f"Greater {np.greater(arr1,arr2)}")

[1 2 3]
[2 1 4]
Greater [False  True False]


In [8]:
print(np.arange(30,71,2))

[30 32 34 36 38 40 42 44 46 48 50 52 54 56 58 60 62 64 66 68 70]


In [9]:
print(np.identity(3,int))

[[1 0 0]
 [0 1 0]
 [0 0 1]]


In [10]:
array_5 = np.arange(21)
print(array_5)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


In [12]:
array_5[(array_5>9) & (array_5 <= 15)] *= -1

In [13]:
print(array_5)

[  0   1   2   3   4   5   6   7   8   9 -10 -11 -12 -13 -14 -15  16  17
  18  19  20]


In [19]:
array_6 =np.diag(np.arange(1,6))
print(array_6)

[[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]
 [0 0 0 0 5]]


In [24]:
print(np.diag([1,2,3,4,5]))

[[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]
 [0 0 0 0 5]]
